version: '3'

services:
  protractor-tests:
    build: '.'
    user: "${USER_ID}:${USER_ID}"
    networks:
      - selenium_net
    depends_on: 
      - selenium
    environment:
      - HOME=.
    volumes:
      - ${PWD}:/workspace
  
  selenium:
    image: selenium/standalone-chrome-debug:3.11.0
    networks:
      - selenium_net
    user: "${USER_ID}:${USER_ID}"
    ports:
      - '4444'
      - '5900'

networks:
  selenium_net:
    driver: bridge
